version: "3.9"

services:
  frontend:
    build:
      context: ./DiseaseMutationsApp
      dockerfile: Dockerfile
    image: disease-mutations-frontend:latest
    container_name: disease-mutations-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: disease-mutations-backend:latest
    volumes:
      - ./bowtie:/app/bowtie
    tmpfs:
      - /tmp
    container_name: disease-mutations-backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G

  data:
    image: disease-mutations-data:latest
    container_name: disease-mutations-data
    volumes:
      - bowtie-data:/app/bowtie 
    command: tail -f /dev/null 

volumes:
  bowtie-data:
    driver: local 
          
